### ISSUE TITLE
Support solid-based type lidar?

### ISSUE THREAD

**Issue by narutojxl** [jisehua/Degenerate-Detection#2]
Dear author,
Does this system support solid-based type lidar? Thanks a lot!

**Comment by jisehua** [comment]
Hello, thanks for your question.

Honestly, I haven't tested it with solid-state LiDAR, but I believe it is theoretically supported, as our method relies on observing changes in the probability distribution of point cloud information between consecutive frames. This approach is independent of the specific type of LiDAR used.

**Comment by narutojxl** [comment]
Thanks for author kind reply.  Preliminary testing with solid-state lidar data revealed that the trajectory  was not satisfactory. I think I should carefully read the paper and code firstly to understand the principles.
Thanks for open sourced this system!
